services:
  postgres:
    # Light image of postgres
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
      POSTGRES_DB: ${DB_NAME:-sync_db}
    ports:
      - "5432:5432"
    volumes:
      # Connect container with local folder
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      # Gives an environment variable that we can use
      DATABASE_URL: postgres://${DB_USER:-user}:${DB_PASSWORD:-pass}@postgres:5432/${DB_NAME:-sync_db}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  # Volume that saves data from postgres_db
  postgres_data:
